apps/post_app/urls.py
from django.conf.urls import url
from . import views
app_name = 'posts'

urlpatterns = [
    url(r'^home$', views.home, name='home'),
    url(r'^home/post_secret$', views.post_secret, name='post_secret'),
    url(r'^home/add_like/(?P<secret_id>\d+)$', views.add_like, name='add_like'),
    url(r'^home/delete_secret/(?P<secret_id>\d+)$', views.delete_secret, name='delete_secret'),
    url(r'^home/most_likes$', views.most_likes, name='most_likes'),
]

apps/user_app/urls.py
from django.conf.urls import url
from . import views
app_name = 'users'

urlpatterns = [
    url(r'^$', views.index, name='register'),
    url(r'^log_in$', views.log_in, name='log_in'),
    url(r'^register_test$', views.register_test, name='register_test'),
    url(r'^log_in_test$', views.log_in_test, name='log_in_test'),

]

secrets2/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.user_app.urls', namespace='users')),
    url(r'^post/', include('apps.post_app.urls', namespace='posts')),
]

apps/post_app/models.py
from __future__ import unicode_literals
from django.db import models
from ..user_app.models import User

# Create your models here.
class SecretManager(models.Manager):
    def create_secret(self, data, user):
        if not data['secret']:
            return False
        else:
            return self.create(secret=data['secret'], user=user)

class LikeManager(models.Manager):
    def create_like(self, secret, user):
        if self.filter(secret=secret, user=user):
            return False
        else:
            return self.create(secret=secret, user=user)

class Secret(models.Model):
    secret = models.TextField(max_length=2000)
    user = models.ForeignKey(User, related_name='secrets')
    created_at= models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)
    objects = SecretManager()
    def secret_user_likes(self):
        likes = Like.objects.filter(secret=self)
        users = []
        for user in likes:
            users.append(user.user)
        return users


class Like(models.Model):
    secret = models.ForeignKey(Secret, related_name='secret_likes')
    user = models.ForeignKey(User, related_name='user_likes')
    created_at= models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)
    objects = LikeManager()

apps/user_app/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt, re
EMAIL_REGEX = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")

class UserManager(models.Manager):
    def create_user(self, data):
        errors = {}
        if not data['first_name'] or len(data['first_name']) < 2 or not data['last_name'] or len(data['last_name']) < 2:
            errors['name'] = 'Please enter a valid name'
        if not data['email'] or not EMAIL_REGEX.match(data['email']):
            errors['email'] = 'Enter a valid email'
        if self.filter(email=data['email']):
            errors['email_exist'] = 'This email already exist'
        if not data['password'] or len(data['password']) < 4:
            errors['password'] = 'Enter a valid password'
        if not data['confirm_password'] or data['password'] != data['confirm_password']:
            errors['confirm_password'] = 'Password doesnt match'
        if len(errors):
            return errors
        else:
            hash_password = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
            return self.create(first_name=data['first_name'], last_name=data['last_name'], email=data['email'], password=hash_password)


    def validate_user(self, data):
        errors = {}
        if self.filter(email=data['email']):
            user = self.get(email=data['email'])
            hash_password = bcrypt.hashpw(data['password'].encode(), user.password.encode())
            if hash_password == user.password:
                return user
            else:
                errors['password'] = 'Invalid password'
        else:
            errors['email'] = 'Invalid email'
        return errors




# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    email = models.CharField(max_length=25)
    password = models.CharField(max_length=25)
    created_at= models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/post_app/views.py
from django.shortcuts import render, redirect
from ..user_app.models import User
from django.contrib import messages
from .models import Secret, Like

# Create your views here.
def home(request):
    user = User.objects.get(id=request.session['user_id'])
    context = {'user': user, 'secrets': Secret.objects.all().order_by('-created_at'), 'user_likes': Like.objects.filter(user_id=user.id)
                    }
    return render(request, 'post_app/home.html', context)

def post_secret(request):
    user = User.objects.get(id=request.session['user_id'])
    entry = Secret.objects.create_secret(request.POST, user)
    if entry == False:
        messages.add_message(request, messages.INFO, 'Type your secret here', extra_tags='no_secret')
    return redirect('posts:home')


def add_like(request, secret_id):
    user = User.objects.get(id=request.session['user_id'])
    secret = Secret.objects.get(id=secret_id)
    entry = Like.objects.create_like(secret, user)
    return redirect('posts:home')

def delete_secret(request, secret_id):
    secret = Secret.objects.get(id=secret_id)
    secret.delete()
    return redirect('posts:home')

def most_likes(request):
    context = {'secrets': Secret.objects.all().order_by('-secret_likes')}
    return render(request, 'post_app/popular.html', context)

apps/user_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User

# Create your views here.
def index(request):
    return render(request, 'user_app/index.html')

def log_in(request):
    return render(request, 'user_app/log_in.html')

def register_test(request):
    entry = User.objects.create_user(request.POST)
    if not type(entry) is dict:
        request.session['user_id'] = entry.id
        return redirect('posts:home')
    else:
        if 'name' in entry:
            messages.add_message(request, messages.INFO, entry['name'], extra_tags='sign_up')
        if 'email' in entry:
            messages.add_message(request, messages.INFO, entry['email'], extra_tags='sign_up')
        if 'password' in entry:
            messages.add_message(request, messages.INFO, entry['password'], extra_tags='sign_up')
        if 'confirm_password' in entry:
            messages.add_message(request, messages.INFO, entry['confirm_password'], extra_tags='sign_up')
        if 'email_exist' in entry:
            messages.add_message(request, messages.INFO, entry['email_exist'], extra_tags='sign_up')
        return redirect('users:register')

def log_in_test(request):
    entry = User.objects.validate_user(request.POST)
    if not type(entry) is dict:
        request.session['user_id'] = entry.id
        return redirect('posts:home')
    else:
        if 'email' in entry:
            messages.add_message(request, messages.INFO, entry['email'], extra_tags='log_in')
        if 'password' in entry:
            messages.add_message(request, messages.INFO, entry['password'], extra_tags='log_in')
        return redirect('users:log_in')    

apps/post_app/templates/post_app/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <style media="screen">
      span{
        color: pink;
      }
    </style>
  </head>
  <body>
      {{user_likes}}
      {{non_likes}}
    <p><a href="{% url 'users:log_in' %}">Sign Out</a></p>
    <h1>Hello {{user.first_name}}  {{user.id}}</h1>
    <p><a href="{% url 'posts:most_likes' %}">Top Secrets</a></p>
    <form action="{% url 'posts:post_secret' %}" method="post">
      <p>Post your secret here</p>
      {% csrf_token %}
      <textarea name="secret" rows="8" cols="80"></textarea>
      {% if messages %}
        {% for message in messages %}
          {% if 'no_secret' in message.tags %}
             <p>{{message}}</p>
          {% endif %}
        {% endfor %}
      {% endif %}
      <input type="submit" value="Post">

      {% for secret in secrets %}
        {% if secret.user.id == user.id %}
          <p>{{secret.user.first_name}} said {{secret.secret}} {{secret.created_at}}<a href="{% url 'posts:delete_secret' secret_id=secret.id %}">Delete</a></p>
        {% else %}
        {% if user in secret.secret_user_likes %}

            <p>{{secret.user.first_name}} said {{secret.secret}} {{secret.created_at}} <span>{{secret.secret_likes.count}}</span> <a href="">Dislike</a></p>
        {% else %}

            <p>{{secret.user.first_name}} said {{secret.secret}} {{secret.created_at}} <span>{{secret.secret_likes.count}}</span> <a href="{% url 'posts:add_like' secret_id=secret.id %}">Like</a></p>
        {% endif %}
        {% endif %}
      {% endfor %}





    </form>
  </body>
</html>

apps/post_app/templates/post_app/popular.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% for secret in secrets %}
    {% if secret.user.id == user.id %}
      <p>{{secret.secret}} {{secret.created_at}}<a href="{% url 'posts:delete_secret' secret_id=secret.id %}">Delete</a></p>
    {% else %}
        <p>{{secret.secret}} {{secret.created_at}} <span>{{secret.secret_likes.count}}</span> <a href="{% url 'posts:add_like' secret_id=secret.id %}">Like</a></p>
    {% endif %}
    {% endfor %}
  </body>
</html>

apps/user_app/templates/user_app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h2>Sign Up</h2>
    <form  action="{% url 'users:register_test' %}" method="post">
      {% csrf_token %}
      <input type="text" name="first_name" placeholder="first name"><p></p>
      <input type="text" name="last_name" placeholder="last name"><p></p>
      <input type="email" name="email" placeholder="email address"><p></p>
      <input type="text" name="password"  placeholder="password"><p></p>
      <input type="text" name="confirm_password"  placeholder="confirm password"><p></p>
      <input type="submit" value="Register">
    </form>
    {% if messages %}
      {% for message in messages %}
        {% if 'sign_up' in message.tags %}
           <p>{{message}}</p>
        {% endif %}
      {% endfor %}
    {% endif %}
    <p><a href="{% url 'users:log_in' %}">Already have an account? Login</a></p>
  </body>
</html>

apps/user_app/templates/user_app/log_in.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h2>Sign In</h2>
    <form  action="{% url 'users:log_in_test' %}" method="post">
      {% csrf_token %}
      <input type="email" name="email" placeholder="email address"><p></p>
      <input type="text" name="password" placeholder="password"><p></p>
      <input type="submit" value="Sign In"><p></p>
      {% if messages %}
        {% for message in messages %}
          {% if 'log_in' in message.tags %}
             <p>{{message}}</p>
          {% endif %}
        {% endfor %}
      {% endif %}
    </form>
    <p><a href="{% url 'users:register' %}">Dont have an account? Register</a></p>
  </body>
</html>